// ProAttend PRO Final
const firebaseConfig={apiKey:"AIzaSyD3Hmy7YU6ELzAJJXgVW62-4ObXiN1s7WM",authDomain:"proattend-3fd57.firebaseapp.com",projectId:"proattend-3fd57",storageBucket:"proattend-3fd57.firebasestorage.app",messagingSenderId:"900289815282",appId:"1:900289815282:web:a98c671680118bb36da66b"};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();
const KEY={emp:"pa_emp_pro",att:"pa_att_pro",leave:"pa_leave_pro",hol:"pa_hol_pro",ot:"pa_ot_pro",settings:"pa_settings_pro"};
let employees=[],attendance=[],leaves=[],holidays=[],overtimes=[],settings={},page="dashboard";

const seedEmployees=[
{id:"EMP-001",name:"Juan Dela Cruz",department:"Operations",position:"Staff",rate:650,status:"Active",schedule:"08:00-17:00",restDay:"Sunday"},
{id:"EMP-002",name:"Maria Santos",department:"Finance",position:"Accountant",rate:750,status:"Active",schedule:"08:00-17:00",restDay:"Saturday"},
{id:"EMP-003",name:"Pedro Reyes",department:"Operations",position:"Supervisor",rate:850,status:"Active",schedule:"08:00-17:00",restDay:"Sunday"},
{id:"EMP-4",name:"Melymar Tabalno",department:"Online Shopping",position:"Online shopping incharge",rate:650,status:"Active",schedule:"08:00-17:00",restDay:"Sunday"}];
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const today=()=>new Date().toISOString().slice(0,10), money=n=>"₱"+Number(n||0).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2}), now=()=>new Date().toLocaleTimeString("en-PH",{hour:"2-digit",minute:"2-digit",hour12:false});
function toast(s){const d=document.createElement("div");d.className="toast";d.textContent=s;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function load(){employees=JSON.parse(localStorage.getItem(KEY.emp)||"null")||seedEmployees.map(x=>({...x}));attendance=JSON.parse(localStorage.getItem(KEY.att)||"[]");leaves=JSON.parse(localStorage.getItem(KEY.leave)||"[]");holidays=JSON.parse(localStorage.getItem(KEY.hol)||"[]");overtimes=JSON.parse(localStorage.getItem(KEY.ot)||"[]");settings=JSON.parse(localStorage.getItem(KEY.settings)||"null")||{company:"ProAttend Company",hours:8,otMultiplier:1.25,lateDeduct:true}}
function save(){localStorage.setItem(KEY.emp,JSON.stringify(employees));localStorage.setItem(KEY.att,JSON.stringify(attendance));localStorage.setItem(KEY.leave,JSON.stringify(leaves));localStorage.setItem(KEY.hol,JSON.stringify(holidays));localStorage.setItem(KEY.ot,JSON.stringify(overtimes));localStorage.setItem(KEY.settings,JSON.stringify(settings))}
function emp(id){return employees.find(x=>x.id===id)}function att(id,d=today()){return attendance.find(x=>x.employeeId===id&&x.date===d)}
function hrs(a){if(!a?.timeIn||!a?.timeOut)return 0;let [ih,im]=a.timeIn.split(":").map(Number),[oh,om]=a.timeOut.split(":").map(Number);return Math.max(0,(oh*60+om-ih*60-im)/60)}
function late(e,a){if(!a?.timeIn)return 0;let st=(e.schedule||"08:00").split("-")[0],[sh,sm]=st.split(":").map(Number),[ih,im]=a.timeIn.split(":").map(Number);return Math.max(0,ih*60+im-sh*60-sm)}
function reg(e,a){return Math.min(hrs(a),Number(settings.hours||8))}function otHours(e,a){return Math.max(0,hrs(a)-Number(settings.hours||8))}
function openModal(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}
$("modalClose").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};

function setPage(p){page=p;document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));render();$("sidebar").classList.remove("open")}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>setPage(x.dataset.page));$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");

function render(){({dashboard:dashboard,employees:employeesPage,attendance:attendancePage,leave:leavePage,holidays:holidaysPage,overtime:overtimePage,payroll:payrollPage,payslip:payslipPage,reports:reportsPage,users:usersPage,settings:settingsPage}[page]||dashboard)()}

function dashboard(){
let d=today(),present=employees.filter(e=>att(e.id,d)?.timeIn).length,lateN=employees.filter(e=>late(e,att(e.id,d))>0).length,abs=employees.length-present,clock=employees.filter(e=>att(e.id,d)?.timeIn&&!att(e.id,d)?.timeOut).length;
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Overview</div><h1>Dashboard</h1><div class="muted">${new Date().toLocaleDateString("en-PH",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</div></div><div class="actions"><button class="btn primary" onclick="openEmployee()">+ Add Employee</button><button class="btn" onclick="render()">Refresh</button></div></div>
<div class="grid"><div class="card"><div class="stat-label">Total Employees</div><div class="stat-value">${employees.length}</div></div><div class="card"><div class="stat-label">Present Today</div><div class="stat-value">${present}</div></div><div class="card"><div class="stat-label">Late Today</div><div class="stat-value">${lateN}</div></div><div class="card"><div class="stat-label">Absent</div><div class="stat-value">${abs}</div></div><div class="card"><div class="stat-label">Clocked In</div><div class="stat-value">${clock}</div></div><div class="card"><div class="stat-label">Daily Payroll Estimate</div><div class="stat-value">${money(employees.filter(e=>att(e.id,d)?.timeIn).reduce((s,e)=>s+Number(e.rate||0),0))}</div></div><div class="card"><div class="stat-label">Leave Requests</div><div class="stat-value">${leaves.filter(x=>x.status==="Pending").length}</div></div><div class="card"><div class="stat-label">OT Requests</div><div class="stat-value">${overtimes.filter(x=>x.status==="Pending").length}</div></div></div>
<div class="card section"><div class="section-title"><h2>Today's Attendance</h2><button class="btn" onclick="setPage('attendance')">Open Attendance</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Department</th><th>Time In</th><th>Time Out</th><th>Late</th><th>Status</th></tr></thead><tbody>${employees.map(e=>{let a=att(e.id,d),s=a?.timeIn?(a.timeOut?"Present":"Clocked In"):"Absent";return `<tr><td><b>${esc(e.name)}</b><br><span class="muted">${esc(e.id)}</span></td><td>${esc(e.department)}</td><td>${a?.timeIn||"—"}</td><td>${a?.timeOut||"—"}</td><td>${late(e,a)} min</td><td><span class="badge ${s==="Absent"?"danger":s==="Clocked In"?"warn":"ok"}">${s}</span></td></tr>`}).join("")}</tbody></table></div></div>`}

function employeesPage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">People</div><h1>Employees</h1><div class="muted">${employees.length} employee(s)</div></div><button class="btn primary" onclick="openEmployee()">+ Add Employee</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Department</th><th>Position</th><th>Rate</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>${employees.map(e=>`<tr><td>${esc(e.id)}</td><td><b>${esc(e.name)}</b></td><td>${esc(e.department)}</td><td>${esc(e.position)}</td><td>${money(e.rate)}</td><td>${esc(e.schedule)}</td><td><span class="badge ${e.status==="Active"?"ok":"danger"}">${esc(e.status)}</span></td><td><button class="btn small" onclick="openEmployee('${esc(e.id)}')">Edit</button> <button class="btn danger small" onclick="deleteEmployee('${esc(e.id)}')">Delete</button></td></tr>`).join("")}</tbody></table></div></div>`}
window.openEmployee=function(id=""){let e=id?emp(id):{id:"",name:"",department:"",position:"",rate:0,status:"Active",schedule:"08:00-17:00",restDay:"Sunday"};openModal(`<h2>${id?"Edit":"Add"} Employee</h2><form id="empForm"><div class="form-grid"><div class="field"><label>Employee ID</label><input name="id" required value="${esc(e.id)}" ${id?"readonly":""}></div><div class="field"><label>Status</label><select name="status"><option ${e.status==="Active"?"selected":""}>Active</option><option ${e.status==="Inactive"?"selected":""}>Inactive</option></select></div><div class="field"><label>Full Name</label><input name="name" required value="${esc(e.name)}"></div><div class="field"><label>Department</label><input name="department" value="${esc(e.department)}"></div><div class="field"><label>Position</label><input name="position" value="${esc(e.position)}"></div><div class="field"><label>Daily Rate</label><input name="rate" type="number" min="0" step=".01" value="${e.rate}"></div><div class="field"><label>Schedule</label><input name="schedule" value="${esc(e.schedule)}"></div><div class="field"><label>Rest Day</label><select name="restDay">${["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map(x=>`<option ${e.restDay===x?"selected":""}>${x}</option>`).join("")}</select></div></div><button class="btn primary wide" type="submit">Save Employee</button></form>`);$("empForm").onsubmit=async ev=>{ev.preventDefault();let o=Object.fromEntries(new FormData(ev.target));o.rate=Number(o.rate)||0;let i=employees.findIndex(x=>x.id===o.id);if(i>=0)employees[i]=o;else employees.push(o);save();try{await db.collection("employees").doc(o.id).set(o)}catch(e){}closeModal();toast("Employee saved");render()}}
window.deleteEmployee=async function(id){if(!confirm("Delete this employee?"))return;employees=employees.filter(e=>e.id!==id);save();try{await db.collection("employees").doc(id).delete()}catch(e){}toast("Employee deleted");render()}

function attendancePage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">DTE</div><h1>Attendance / Daily Time Entry</h1><div class="muted">${today()}</div></div><button class="btn" onclick="window.print()">Print DTE</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Schedule</th><th>Time In</th><th>Time Out</th><th>Regular</th><th>Late</th><th>OT</th><th>Action</th></tr></thead><tbody>${employees.map(e=>{let a=att(e.id);return `<tr><td><b>${esc(e.name)}</b><br><span class="muted">${e.id}</span></td><td>${esc(e.schedule)}</td><td>${a?.timeIn||"—"}</td><td>${a?.timeOut||"—"}</td><td>${reg(e,a).toFixed(2)}</td><td>${late(e,a)} min</td><td>${otHours(e,a).toFixed(2)}</td><td>${!a?.timeIn?`<button class="btn ok small" onclick="clockIn('${e.id}')">Time In</button>`:!a?.timeOut?`<button class="btn warn small" onclick="clockOut('${e.id}')">Time Out</button>`:`<span class="badge ok">Complete</span>`}</td></tr>`}).join("")}</tbody></table></div></div>`}
async function write(col,row){try{await db.collection(col).doc(row.key||row.id).set(row)}catch(e){console.warn(e)}}
window.clockIn=async id=>{let row={key:id+"_"+today(),employeeId:id,date:today(),timeIn:now(),timeOut:"",type:"attendance"};let i=attendance.findIndex(x=>x.key===row.key);if(i>=0)attendance[i]=row;else attendance.push(row);save();await write("attendance",row);toast("Time In recorded");attendancePage()}
window.clockOut=async id=>{let a=att(id);if(!a)return;a.timeOut=now();save();await write("attendance",a);toast("Time Out recorded");attendancePage()}

function leavePage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Leave</div><h1>Leave Management</h1></div><button class="btn primary" onclick="openLeave()">+ Leave Request</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Type</th><th>From</th><th>To</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>${leaves.length?leaves.map(x=>`<tr><td>${esc(emp(x.employeeId)?.name||x.employeeId)}</td><td>${esc(x.type)}</td><td>${x.from}</td><td>${x.to}</td><td>${esc(x.reason)}</td><td><span class="badge ${x.status==="Approved"?"ok":x.status==="Rejected"?"danger":"warn"}">${x.status}</span></td><td>${x.status==="Pending"?`<button class="btn ok small" onclick="setLeave('${x.key}','Approved')">Approve</button> <button class="btn danger small" onclick="setLeave('${x.key}','Rejected')">Reject</button>`:"—"}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">No leave requests.</td></tr>`}</tbody></table></div></div>`}
window.openLeave=function(){openModal(`<h2>Leave Request</h2><form id="leaveForm"><div class="form-grid"><div class="field"><label>Employee</label><select name="employeeId">${employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("")}</select></div><div class="field"><label>Leave Type</label><select name="type"><option>Vacation</option><option>Sick</option><option>Emergency</option><option>Other</option></select></div><div class="field"><label>From</label><input type="date" name="from" required></div><div class="field"><label>To</label><input type="date" name="to" required></div><div class="field full"><label>Reason</label><textarea name="reason"></textarea></div></div><button class="btn primary wide">Submit Request</button></form>`);$("leaveForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.key="L"+Date.now();o.status="Pending";leaves.push(o);save();await write("leaves",o);closeModal();toast("Leave request added");render()}}
window.setLeave=async(k,s)=>{let x=leaves.find(x=>x.key===k);if(x){x.status=s;save();await write("leaves",x);render()}}

function holidaysPage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Calendar</div><h1>Holidays</h1></div><button class="btn primary" onclick="openHoliday()">+ Add Holiday</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Name</th><th>Type</th><th>Action</th></tr></thead><tbody>${holidays.length?holidays.map(x=>`<tr><td>${x.date}</td><td>${esc(x.name)}</td><td>${esc(x.type)}</td><td><button class="btn danger small" onclick="deleteHoliday('${x.key}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="4" class="empty">No holidays added.</td></tr>`}</tbody></table></div></div>`}
window.openHoliday=function(){openModal(`<h2>Add Holiday</h2><form id="holForm"><div class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required></div><div class="field"><label>Holiday Name</label><input name="name" required></div><div class="field"><label>Type</label><select name="type"><option>Regular</option><option>Special Non-Working</option><option>Company</option></select></div></div><button class="btn primary wide">Save Holiday</button></form>`);$("holForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.key="H"+Date.now();holidays.push(o);save();await write("holidays",o);closeModal();render()}}
window.deleteHoliday=async k=>{holidays=holidays.filter(x=>x.key!==k);save();try{await db.collection("holidays").doc(k).delete()}catch(e){}render()}

function overtimePage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Overtime</div><h1>Overtime Management</h1></div><button class="btn primary" onclick="openOT()">+ OT Request</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Date</th><th>Hours</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>${overtimes.length?overtimes.map(x=>`<tr><td>${esc(emp(x.employeeId)?.name||x.employeeId)}</td><td>${x.date}</td><td>${x.hours}</td><td>${esc(x.reason)}</td><td><span class="badge ${x.status==="Approved"?"ok":x.status==="Rejected"?"danger":"warn"}">${x.status}</span></td><td>${x.status==="Pending"?`<button class="btn ok small" onclick="setOT('${x.key}','Approved')">Approve</button> <button class="btn danger small" onclick="setOT('${x.key}','Rejected')">Reject</button>`:"—"}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">No overtime requests.</td></tr>`}</tbody></table></div></div>`}
window.openOT=function(){openModal(`<h2>Overtime Request</h2><form id="otForm"><div class="form-grid"><div class="field"><label>Employee</label><select name="employeeId">${employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("")}</select></div><div class="field"><label>Date</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>Hours</label><input name="hours" type="number" min="0" step=".25" required></div><div class="field"><label>Reason</label><input name="reason"></div></div><button class="btn primary wide">Submit OT</button></form>`);$("otForm").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.hours=Number(o.hours)||0;o.key="OT"+Date.now();o.status="Pending";overtimes.push(o);save();await write("overtime",o);closeModal();render()}}
window.setOT=async(k,s)=>{let x=overtimes.find(x=>x.key===k);if(x){x.status=s;save();await write("overtime",x);render()}}

function payrollRows(){return employees.map(e=>{let a=att(e.id),r=reg(e,a),ot=otHours(e,a),lateMin=late(e,a),hourly=Number(e.rate||0)/Number(settings.hours||8),otPay=ot*hourly*Number(settings.otMultiplier||1.25),lateDed=settings.lateDeduct?(lateMin/60)*hourly:0;let approvedOT=overtimes.filter(x=>x.employeeId===e.id&&x.status==="Approved").reduce((s,x)=>s+Number(x.hours||0),0);otPay+=approvedOT*hourly*Number(settings.otMultiplier||1.25);let gross=a?.timeIn?Number(e.rate||0)+otPay-lateDed:0;return {e,a,r,ot,lateMin,otPay,lateDed,gross}})}
function payrollPage(){
let rows=payrollRows(),gross=rows.reduce((s,x)=>s+x.gross,0);
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Payroll</div><h1>Payroll</h1><div class="muted">Current attendance/payroll period: ${today()}</div></div><button class="btn" onclick="window.print()">Print Payroll</button></div><div class="summary"><div class="mini">Employees <b>${employees.length}</b></div><div class="mini">Gross Total <b>${money(gross)}</b></div><div class="mini">OT Multiplier <b>${settings.otMultiplier}×</b></div></div><div class="card section"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Rate</th><th>Reg Hrs</th><th>Late</th><th>OT Pay</th><th>Late Ded.</th><th>Gross</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.e.name)}</b><br><span class="muted">${x.e.id}</span></td><td>${money(x.e.rate)}</td><td>${x.r.toFixed(2)}</td><td>${x.lateMin} min</td><td>${money(x.otPay)}</td><td>${money(x.lateDed)}</td><td><b>${money(x.gross)}</b></td></tr>`).join("")}</tbody></table></div></div><div class="card section"><b>Payroll base:</b> daily rate when present + approved OT − late deduction. Add your company-specific statutory deductions, allowances, holiday/rest-day and night-differential rules before production payroll use.</div>`}

function payslipPage(){
let opts=employees.map(e=>`<option value="${e.id}">${esc(e.name)} — ${e.id}</option>`).join("");
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Payslip</div><h1>Payslip Generator</h1><div class="muted">Select an employee and generate a printable payslip.</div></div></div><div class="card"><div class="form-grid"><div class="field"><label>Employee</label><select id="slipEmp">${opts}</select></div><div class="field"><label>Period</label><input id="slipPeriod" value="${today()}"></div></div><button class="btn primary wide" onclick="generateSlip()">Generate Payslip</button></div><div id="slipResult" class="section"></div>`}
window.generateSlip=function(){let e=emp($("slipEmp").value),r=payrollRows().find(x=>x.e.id===e.id),p=$("slipPeriod").value;$("slipResult").innerHTML=`<div class="card"><div class="section-title"><h2>${esc(settings.company)}</h2><button class="btn" onclick="window.print()">Print</button></div><p><b>Payslip</b><br>Employee: ${esc(e.name)} (${e.id})<br>Period: ${esc(p)}</p><hr><div class="summary"><div class="mini">Daily Rate<b>${money(e.rate)}</b></div><div class="mini">OT Pay<b>${money(r.otPay)}</b></div><div class="mini">Late Deduction<b>${money(r.lateDed)}</b></div><div class="mini">Gross Pay<b>${money(r.gross)}</b></div></div><p class="muted">Net pay requires configured deductions/allowances and is not calculated as a statutory payroll amount in this base version.</p></div>`}

function reportsPage(){
let present=employees.filter(e=>att(e.id)?.timeIn).length,totalHours=employees.reduce((s,e)=>s+hrs(att(e.id)),0),lateM=employees.reduce((s,e)=>s+late(e,att(e.id)),0);
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Reports</div><h1>Reports & Summary</h1></div><button class="btn" onclick="window.print()">Print Report</button></div><div class="grid"><div class="card"><div class="stat-label">Employees</div><div class="stat-value">${employees.length}</div></div><div class="card"><div class="stat-label">Present Today</div><div class="stat-value">${present}</div></div><div class="card"><div class="stat-label">Total Hours Today</div><div class="stat-value">${totalHours.toFixed(2)}</div></div><div class="card"><div class="stat-label">Late Minutes</div><div class="stat-value">${lateM}</div></div></div><div class="card section"><h2>Available Reports</h2><p>Attendance/DTE, Payroll, Payslip, Leave and Overtime are available from the menu and can be printed from the corresponding page.</p></div>`}

function usersPage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Security</div><h1>Users / Roles</h1><div class="muted">Firebase Authentication controls login accounts. Role profiles below are for application planning and display.</div></div></div><div class="card"><table class="table"><thead><tr><th>Role</th><th>Access</th></tr></thead><tbody><tr><td><span class="badge info">Admin</span></td><td>Full system access, employee management, payroll, reports and settings.</td></tr><tr><td><span class="badge ok">HR / Payroll</span></td><td>Employees, attendance, leave, overtime, payroll and reports.</td></tr><tr><td><span class="badge warn">Employee</span></td><td>Own attendance, DTE, leave and payslip views when employee authentication is connected.</td></tr></tbody></table></div><div class="card section"><b>Current Firebase login:</b> the signed-in Firebase account is authenticated. For true production role enforcement, add a Firestore user-role document/custom claims and tighten Firestore security rules.</div>`}

function settingsPage(){
$("content").innerHTML=`<div class="page-head"><div><div class="kicker">Configuration</div><h1>System Settings</h1></div></div><div class="card"><form id="settingsForm"><div class="form-grid"><div class="field"><label>Company Name</label><input name="company" value="${esc(settings.company)}"></div><div class="field"><label>Regular Hours / Day</label><input name="hours" type="number" min="1" max="24" value="${settings.hours}"></div><div class="field"><label>OT Multiplier</label><input name="otMultiplier" type="number" min="1" step=".05" value="${settings.otMultiplier}"></div><div class="field"><label>Late Deduction</label><select name="lateDeduct"><option value="true" ${settings.lateDeduct?"selected":""}>Enabled</option><option value="false" ${!settings.lateDeduct?"selected":""}>Disabled</option></select></div></div><button class="btn primary wide">Save Settings</button></form></div><div class="card section"><b>Data:</b> local browser data is used as a fallback/cache. Employees, attendance and request records also attempt Firestore synchronization when authenticated.</div>`;$("settingsForm").onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));settings={company:o.company,hours:Number(o.hours)||8,otMultiplier:Number(o.otMultiplier)||1.25,lateDeduct:o.lateDeduct==="true"};save();toast("Settings saved");render()}}

async function syncCloud(){
try{let s=await db.collection("employees").get();if(!s.empty){let m=new Map(employees.map(x=>[x.id,x]));s.docs.forEach(d=>m.set(d.id,d.data()));employees=[...m.values()];save()}else for(const e of employees)await db.collection("employees").doc(e.id).set(e)}catch(e){console.warn("employee sync",e)}
try{let s=await db.collection("attendance").limit(500).get();if(!s.empty){attendance=s.docs.map(d=>d.data());save()}}catch(e){console.warn("attendance sync",e)}
}

async function ensureAnonymous(){
  if(auth.currentUser) return auth.currentUser;
  try { return await auth.signInAnonymously(); }
  catch(e){ throw new Error("Anonymous sign-in is not enabled in Firebase Authentication."); }
}
function showClockPanel(){
  $("clockPanel").classList.remove("hidden");
  $("clockPanel").innerHTML=`<div class="card" style="margin-top:18px"><h3 style="margin:0 0 10px">Employee Time In / Out</h3><p class="muted">Enter your Employee ID. The system will record the current time in Firebase.</p><label>Employee ID</label><input id="clockEmpId" placeholder="e.g. EMP-001" autocomplete="off"><button id="clockCheckBtn" class="btn primary wide">Continue</button><button id="clockBackBtn" class="btn wide" style="margin-top:8px">Back to Admin Login</button><div id="clockMsg" class="message"></div></div>`;
  $("clockBackBtn").onclick=()=>{$("clockPanel").classList.add("hidden");$("loginMessage").textContent=""};
  $("clockCheckBtn").onclick=employeeClockAction;
}
async function employeeClockAction(){
  const id=$("clockEmpId").value.trim();
  const msg=$("clockMsg"); msg.textContent="";
  if(!id){msg.textContent="Enter your Employee ID.";return}
  try{
    const user=await ensureAnonymous();
    const ref=db.collection("employees").doc(id);
    const snap=await ref.get();
    if(!snap.exists){msg.textContent="Employee ID not found.";return}
    const e=snap.data();
    if(String(e.status||"Active").toLowerCase()!=="active"){msg.textContent="This employee is inactive.";return}
    const key=id+"_"+today(), aref=db.collection("attendance").doc(key);
    const asnap=await aref.get();
    let row=asnap.exists?asnap.data():{key,employeeId:id,date:today(),timeIn:"",timeOut:"",type:"attendance"};
    if(!row.timeIn){
      row.timeIn=now();
      row.timeOut="";
      await aref.set(row);
      attendance=attendance.filter(x=>x.key!==key); attendance.push(row); save();
      msg.innerHTML=`<span class="badge ok">TIME IN RECORDED</span><br><br>${esc(e.name)} — ${row.timeIn}`;
    }else if(!row.timeOut){
      row.timeOut=now();
      await aref.set(row);
      attendance=attendance.filter(x=>x.key!==key); attendance.push(row); save();
      msg.innerHTML=`<span class="badge ok">TIME OUT RECORDED</span><br><br>${esc(e.name)} — ${row.timeOut}`;
    }else{
      msg.innerHTML=`<span class="badge info">ALREADY COMPLETE</span><br><br>Time In: ${row.timeIn}<br>Time Out: ${row.timeOut}`;
    }
  }catch(e){console.error(e);msg.textContent=e.message||"Unable to record attendance."}
}
$("employeeClockBtn").onclick=showClockPanel;


// Employee self-service kiosk (Firebase anonymous authentication)
$("employeeClockBtn").onclick=()=>{$("loginScreen").classList.add("hidden");$("employeeClock").classList.remove("hidden");$("clockEmployeeId").focus()};
$("clockBack").onclick=()=>{$("employeeClock").classList.add("hidden");$("loginScreen").classList.remove("hidden");$("clockMessage").textContent="";$("clockPanel").classList.add("hidden")};
$("clockContinue").onclick=async()=>{
  const id=$("clockEmployeeId").value.trim();
  $("clockMessage").textContent="";
  $("clockPanel").classList.add("hidden");
  if(!id){$("clockMessage").textContent="Enter your Employee ID.";return}
  try{
    await auth.signInAnonymously();
    const snap=await db.collection("employees").doc(id).get();
    if(!snap.exists || snap.data().status==="Inactive") throw new Error("Employee ID not found or inactive.");
    const e=snap.data(), key=id+"_"+today(), ref=db.collection("attendance").doc(key), as=await ref.get(), a=as.exists?as.data():null;
    $("clockPanel").innerHTML=`<div class="card"><div class="kicker">Employee</div><div class="kiosk-name">${esc(e.name)}</div><div class="muted">${esc(e.department||"")} • ${esc(e.position||"")}</div><div class="section"><b>Today:</b> ${today()}<br>Time In: ${a?.timeIn||"—"}<br>Time Out: ${a?.timeOut||"—"}</div><div class="clock-buttons">${!a?.timeIn?`<button class="btn primary" id="kIn">Time In</button>`:!a?.timeOut?`<button class="btn warn" id="kOut">Time Out</button>`:`<button class="btn" disabled>Attendance Complete</button>`}<button class="btn" id="kDone">Done</button></div></div>`;
    $("clockPanel").classList.remove("hidden");
    if($("kIn"))$("kIn").onclick=async()=>{const row={key,employeeId:id,date:today(),timeIn:now(),timeOut:"",type:"attendance"};await ref.set(row);$("clockMessage").textContent="Time In recorded successfully.";await showKiosk(id)};
    if($("kOut"))$("kOut").onclick=async()=>{const row={...a,timeOut:now()};await ref.set(row);$("clockMessage").textContent="Time Out recorded successfully.";await showKiosk(id)};
    $("kDone").onclick=()=>{$("clockEmployeeId").value="";$("clockPanel").classList.add("hidden");$("clockMessage").textContent="Done. You may enter another Employee ID."};
  }catch(err){$("clockMessage").textContent=err.message||"Unable to connect to Firebase."}
};
async function showKiosk(id){const snap=await db.collection("employees").doc(id).get(),e=snap.data(),as=await db.collection("attendance").doc(id+"_"+today()).get(),a=as.exists?as.data():null;$("clockPanel").innerHTML=`<div class="card"><div class="kicker">Employee</div><div class="kiosk-name">${esc(e.name)}</div><div class="section">Time In: ${a?.timeIn||"—"}<br>Time Out: ${a?.timeOut||"—"}</div><div class="clock-buttons">${!a?.timeIn?`<button class="btn primary" id="kIn">Time In</button>`:!a?.timeOut?`<button class="btn warn" id="kOut">Time Out</button>`:`<button class="btn" disabled>Attendance Complete</button>`}<button class="btn" id="kDone">Done</button></div></div>`;$("kDone").onclick=()=>$("clockPanel").classList.add("hidden");if($("kIn"))$("kIn").onclick=async()=>{await db.collection("attendance").doc(id+"_"+today()).set({key:id+"_"+today(),employeeId:id,date:today(),timeIn:now(),timeOut:"",type:"attendance"});$("clockMessage").textContent="Time In recorded successfully.";showKiosk(id)};if($("kOut"))$("kOut").onclick=async()=>{let x=a;x.timeOut=now();await db.collection("attendance").doc(id+"_"+today()).set(x);$("clockMessage").textContent="Time Out recorded successfully.";showKiosk(id)}}
$("loginBtn").onclick=async()=>{let email=$("loginEmail").value.trim(),pass=$("loginPassword").value;$("loginMessage").textContent="";if(!email||!pass){$("loginMessage").textContent="Enter email and password.";return}$("loginBtn").disabled=true;$("loginBtn").textContent="Logging in…";try{await auth.signInWithEmailAndPassword(email,pass)}catch(e){$("loginMessage").textContent="Invalid email or password."}finally{$("loginBtn").disabled=false;$("loginBtn").textContent="Login"}};
$("logoutBtn").onclick=async()=>{await auth.signOut();location.reload()};
auth.onAuthStateChanged(async user=>{if(!user){$("app").classList.add("hidden");$("loginScreen").classList.remove("hidden");return}$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("userEmail").textContent=user.email||"";load();render();await syncCloud();render()});
window.addEventListener("error",e=>{console.error(e.error||e.message);if(!$("app").classList.contains("hidden"))toast("App error: "+e.message)});
